name: Staging build+deploy

on:
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: 'Environment (stable, unstable, sandbox)'
        default: 'unstable'
        required: true

jobs:
  validate-args:
    name: Validate arguments
    runs-on: ubuntu-latest
    steps:
      - name: Valid deploy environment
        run: |
         if ! [[ "${{ github.event.inputs.deploy_environment }}" =~ ^(stable|unstable|sandbox)$ ]]; then echo "$env is not a valid deploy environment" && exit 1 ; fi

  deploy-staging:
    name: Deploy Staging
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.deploy_environment }}
    needs: validate-args
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      -
        name: Setup Node with Private GitHub Registry Access
        uses: actions/setup-node@v2
        with:
          node-version: '14.16.1'
          registry-url: 'https://npm.pkg.github.com'

      -
        name: Build
        env:
          COMMIT_HASH: ${{ github.sha }}
          WEBPACK_ENV: ${{ github.event.inputs.deploy_environment }}
        run: |
          make build-reverb-ui
